# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kv_store.network import kvstore_pb2 as kvstore__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kvstore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVStoreServiceStub(object):
    """KVStoreService defines the gRPC interface for the distributed key-value store.
    It includes client-facing CRUD operations, inter-node replication,
    gossip-based membership exchange, hinted handoff, and anti-entropy sync.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/kvstore.KVStoreService/Put',
                request_serializer=kvstore__pb2.PutRequest.SerializeToString,
                response_deserializer=kvstore__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/kvstore.KVStoreService/Get',
                request_serializer=kvstore__pb2.GetRequest.SerializeToString,
                response_deserializer=kvstore__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/kvstore.KVStoreService/Delete',
                request_serializer=kvstore__pb2.DeleteRequest.SerializeToString,
                response_deserializer=kvstore__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Replicate = channel.unary_unary(
                '/kvstore.KVStoreService/Replicate',
                request_serializer=kvstore__pb2.ReplicateRequest.SerializeToString,
                response_deserializer=kvstore__pb2.ReplicateResponse.FromString,
                _registered_method=True)
        self.GossipExchange = channel.unary_unary(
                '/kvstore.KVStoreService/GossipExchange',
                request_serializer=kvstore__pb2.GossipMessage.SerializeToString,
                response_deserializer=kvstore__pb2.GossipMessage.FromString,
                _registered_method=True)
        self.HintedHandoff = channel.unary_unary(
                '/kvstore.KVStoreService/HintedHandoff',
                request_serializer=kvstore__pb2.HintedHandoffRequest.SerializeToString,
                response_deserializer=kvstore__pb2.HintedHandoffResponse.FromString,
                _registered_method=True)
        self.MerkleTreeSync = channel.unary_unary(
                '/kvstore.KVStoreService/MerkleTreeSync',
                request_serializer=kvstore__pb2.MerkleTreeSyncRequest.SerializeToString,
                response_deserializer=kvstore__pb2.MerkleTreeSyncResponse.FromString,
                _registered_method=True)


class KVStoreServiceServicer(object):
    """KVStoreService defines the gRPC interface for the distributed key-value store.
    It includes client-facing CRUD operations, inter-node replication,
    gossip-based membership exchange, hinted handoff, and anti-entropy sync.
    """

    def Put(self, request, context):
        """Client-facing CRUD operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replicate(self, request, context):
        """Inter-node replication of writes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GossipExchange(self, request, context):
        """Membership list exchange between nodes (gossip protocol)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HintedHandoff(self, request, context):
        """Pushing hinted data back to recovered nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MerkleTreeSync(self, request, context):
        """Anti-entropy synchronization between replicas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=kvstore__pb2.PutRequest.FromString,
                    response_serializer=kvstore__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=kvstore__pb2.GetRequest.FromString,
                    response_serializer=kvstore__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kvstore__pb2.DeleteRequest.FromString,
                    response_serializer=kvstore__pb2.DeleteResponse.SerializeToString,
            ),
            'Replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=kvstore__pb2.ReplicateRequest.FromString,
                    response_serializer=kvstore__pb2.ReplicateResponse.SerializeToString,
            ),
            'GossipExchange': grpc.unary_unary_rpc_method_handler(
                    servicer.GossipExchange,
                    request_deserializer=kvstore__pb2.GossipMessage.FromString,
                    response_serializer=kvstore__pb2.GossipMessage.SerializeToString,
            ),
            'HintedHandoff': grpc.unary_unary_rpc_method_handler(
                    servicer.HintedHandoff,
                    request_deserializer=kvstore__pb2.HintedHandoffRequest.FromString,
                    response_serializer=kvstore__pb2.HintedHandoffResponse.SerializeToString,
            ),
            'MerkleTreeSync': grpc.unary_unary_rpc_method_handler(
                    servicer.MerkleTreeSync,
                    request_deserializer=kvstore__pb2.MerkleTreeSyncRequest.FromString,
                    response_serializer=kvstore__pb2.MerkleTreeSyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.KVStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvstore.KVStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVStoreService(object):
    """KVStoreService defines the gRPC interface for the distributed key-value store.
    It includes client-facing CRUD operations, inter-node replication,
    gossip-based membership exchange, hinted handoff, and anti-entropy sync.
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStoreService/Put',
            kvstore__pb2.PutRequest.SerializeToString,
            kvstore__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStoreService/Get',
            kvstore__pb2.GetRequest.SerializeToString,
            kvstore__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStoreService/Delete',
            kvstore__pb2.DeleteRequest.SerializeToString,
            kvstore__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStoreService/Replicate',
            kvstore__pb2.ReplicateRequest.SerializeToString,
            kvstore__pb2.ReplicateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GossipExchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStoreService/GossipExchange',
            kvstore__pb2.GossipMessage.SerializeToString,
            kvstore__pb2.GossipMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HintedHandoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStoreService/HintedHandoff',
            kvstore__pb2.HintedHandoffRequest.SerializeToString,
            kvstore__pb2.HintedHandoffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MerkleTreeSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStoreService/MerkleTreeSync',
            kvstore__pb2.MerkleTreeSyncRequest.SerializeToString,
            kvstore__pb2.MerkleTreeSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
